reviewers:
  defaults:
    - code-reviewers

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    code-reviewers:
      - DZappala
      - Arcadyi
      - JackEPepper

options:
  ignore_draft: true
  number_of_reviewers: 2
  ignored_keywords:
    - DO NOT REVIEW
  last_files_match_only: false
